### ISSUE TITLE
loosing favs

### ISSUE THREAD

**Issue by ajay-gh** [ivpn/desktop-app#97] opened 2021-11-21 10:05 UTC
# Bug report

## Describe your environment

* Device: macbook pro
* OS name and version: Mojave
* IVPN app version: 3.4.0

## Describe the problem
favorite servers list is lost every couple of days, reassigning favs solves the problem temporarily, but the list 
turns out empty again after a few days (this is not linked to updating the client application)

### Steps to reproduce:

1. use client, and assign favorite servers
2. keep using for a few days
3. try to open favs list

### Observed Results:

list empty
### Expected Results:

* What did you expect to happen?  the list remains filled with my favs forever

### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by stenya** [comment] 2021-11-21 14:24
H @ajay-gh 
Please, let us know if you are using multiple user accounts on your macOS device.
Note: in case of using multiple accounts on the same device - each account will use its own favorite servers list.

@gorkapernas Can you, please, check if we are able to reproduce the issue?

**Comment by ajay-gh** [comment] 2021-11-21 16:39
I can confirm, the problem started some releases ago, and it is still present in 3.4.0
I am not using multiple user account.

**Comment by stenya** [comment] 2021-11-21 17:08
@ajay-gh Just to clarify... Does it mean that problem appeared in earlier release (not 3.4.0)?

**Comment by ajay-gh** [comment] 2021-11-21 18:32
I believe it started in 3.2.0, but not sure. It is not a problem new in 3.4.0.

**Comment by nschonni** [comment] 2021-11-28 17:47
I also see this, but the part where it appears is between version releases. Both Windows and macOS

**Comment by stenya** [comment] 2022-05-18 11:47
I am unable to reproduce this issue.
@gorkapernas Can you, please, keep your eyes on it?

**Comment by ajay-gh** [comment] 2022-05-18 15:01
Just updated to 3.7.0. (for osx), and again all favs gone. But I also noticed that there seem to be two separate fav lists, one for openvpn and one for wireguard. Is this possible ? If so, a switch from one protocol to another (with one list empty) could appear like a loss of favs.

**Comment by stenya** [comment] 2022-05-18 15:18
@ajay-gh Yes. We use separate favorite servers configuration for each protocol.
So, it seems that there is no bug here. I am going to close this ticket soon.

Meanwhile, the latest IVPN version is v3.8.7 ;)

**Comment by stenya** [comment] 2022-05-19 09:41
I am closing the ticket.
Feel free to reopen it if necessary.

**Closed by stenya** 2022-05-19 09:41 UTC
