### ISSUE TITLE
(Linux) Split tunneling fails

### ISSUE THREAD

**Issue by 3isfee** [ivpn/desktop-app#287] opened 2023-06-20 19:17 UTC
# Bug report

## Describe your environment

* OS name and version: Nobara Linux 37
* IVPN app version: 3.10.23

## Describe the problem

Without giving the interface name in this command there is an error when trying to start an application via split tunneling.
https://github.com/ivpn/desktop-app/blob/6adeca2f2bd412a361bf6a0ffb9ec63435855519/daemon/References/Linux/etc/splittun.sh#L270

Adding dev ${_def_interface_name} fixes the issue.

### Steps to reproduce:

1. Start IVPN
2. Enable Split Tunneling
3. Try to launch an application

### Observed Results:

This error occurs: 
failed to enable Split Tunneling: (exit status 2) Error: Egress device not specified.

### Expected Results:

Application launches with split tunneling.

**Comment by stenya** [comment] 2023-07-25 12:50
Here's more information about the issue:
- the issue arises on client machines that are connected via IPv6
- the particular Linux distribution is irrelevant. I was able to reproduce the issue on 'Fedora 36'

@gorkapernas The split-tunneling script has been modified. A brief regression test of split-tunneling is required on various Linux distributions.

**Comment by stenya** [comment] 2023-08-16 20:05
@gorkapernas v3.11.18

**Comment by gorkapernas** [comment] 2023-08-21 13:34
Verified fixed on v3.11.18 and 3.12.0, tested Split Tunnelling on different Linux distributions under the conditions described on: https://github.com/ivpn/desktop-app/issues/287#issuecomment-1649780548

Split Tunnelling seems to be working as expected.

**Comment by stenya** [comment] 2023-09-01 07:03
v3.12.0 released

**Closed by stenya** 2023-09-01 07:03 UTC
