### ISSUE TITLE
DNS leaks when systemd-resolved is running

### ISSUE THREAD

**Issue by maltabeeffishrelish** [ivpn/desktop-app#149] opened 2022-04-24 19:23 UTC
# Bug report

## Describe your environment

* Device: Desktop  
* OS name and version: Arch Linux
* IVPN app version: 3.7.0

### Steps to reproduce:

1. systemctl enable --now systemd-resolved
2. Connect to IVPN

### Observed Results:

Whether /etc/resolv.conf is a symbolic link or not, just having resolved running will leak DNS.
Many Linux distributions now use systemd. This is a issue.

### Expected Results:

Allow IVPN and resolved to coexist

### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by stenya** [comment] 2022-05-03 13:47
@maltabeeffishrelish Thank you for the issue report.

Can you, please, let us know how you check that DNS leaking? 
Is the whole system leaking or some software?

**Comment by maltabeeffishrelish** [comment] 2022-05-03 13:50
I confirmed this by opening [this page](https://whoer.net/dns-leak-test) in Firefox.

**Comment by stenya** [comment] 2022-05-03 14:03
Thanks. 
May I ask you to share a screenshot of this page?
_Before doing a screenshot: please ensure that IVPN VPN is connected, custom DNS configuration is disabled in IVPN client settings, and IVPN Firewall is enabled._

**Comment by stenya** [comment] 2022-05-03 14:06
and, please, let us know to which VPN server you were connected when the screenshot was taken.

**Comment by maltabeeffishrelish** [comment] 2022-05-04 06:28
Here is a screenshot of it.
![Screenshot from 2022-05-04 15-26-08](https://user-images.githubusercontent.com/103640181/166632148-76962b45-6f21-4158-9137-96289d30db2e.png)

**Comment by maltabeeffishrelish** [comment] 2022-05-04 06:31
K-Opticom is the residential ISP I subscribe to, AS17511, also known as Optage or eo-Hikari.

**Comment by stenya** [comment] 2022-05-06 15:50
@maltabeeffishrelish The fix is ready already. 
Can I ask you to check if it works for you? If so - I will be very grateful to you.

Here is an instruction on how to install the **beta** version of `ivpn` package on Arch Linux:
1) Download and extract the archive:
[ivpn_beta_3.8.8.tar.gz](https://github.com/ivpn/desktop-app/files/8641881/ivpn_beta_3.8.8.tar.gz)
_SHA256(ivpn_beta_3.8.8.tar.gz)= 9b957c90ffc01cc98ff335511600c6760de4a255244c17c6e0c693032a856163_
2) Open terminal and locate the extracted 'ivpn' folder `cd <path_to_the_folder>\ivpn`
3) Run command to compile and install the package:
`makepkg -sri`
Now you are able to test if the issue is fixed for you. 

Please, note: it is a beta version. In case of any issues, please, install our official version (v3.8.7) back.

**Comment by maltabeeffishrelish** [comment] 2022-05-07 06:35
@stenya 
I just tested it and confirmed that DNS does not leak.

**Comment by stenya** [comment] 2022-05-07 06:40
Thank you for your help!

**Comment by stenya** [comment] 2022-05-10 10:55
@gorkapernas v3.8.9 is ready for testing

**Comment by stenya** [comment] 2022-05-20 11:57
@gorkapernas  v3.8.10 is ready for testing

**Comment by gorkapernas** [comment] 2022-05-25 14:16
Verified fixed on v3.8.10, different Linux distributions and macOS, the issue is no longer reproducible. 
The FW rules have been strengthened, so no more DNS leaks are observed.

**Closed** 2022-06-01 11:34 UTC
Labels: priority: high, type: bug, platform: Linux, Firewall
