### ISSUE TITLE
strange fallback to UDP/port 53

### ISSUE THREAD

**Issue by ajay-gh** [ivpn/desktop-app#263] opened 2023-03-12 12:21 UTC
# Bug report

## Describe your environment

* Device: MacBook Pro
* OS name and version: Monterey
* IVPN app version: 3.10.14

## Describe the problem
Every couple of days (of using iPVN) the client can no longer connect. It took me a while to understand that the problem would always come with one of two scenarios: either the main client window shows that the protocol/port selection has gone "back" to a combination I do never use (see first screen shot) OR the settings window show no port numbers at all (as shown in the 2nd screenshot). I cannot describe steps to reproduce.

### Steps to reproduce:

1. nill

### Observed Results:

When this happens it it sometimes enough to select the standard combination (UDP/port 2049) to bring the client back to connect. But in the second case, only a full restart of osx can solve the problem until it comes back a few days later.
I have tried and used the setting "allow access to iVPN servers ..." as ON, for a few days to see if this solves the problem, but it does not. 

### Expected Results:

* What did you expect to happen?  This should never happen at all.

### Relevant Code:

unknown

**Comment by ajay-gh** [comment] 2023-03-12 12:21
<img width="385" alt="Screen Shot 2023-03-12 at 1 12 05 PM" src="https://user-images.githubusercontent.com/46941311/224544332-35c20acb-1974-47d4-8b35-0661318ef95c.png">
<img width="698" alt="Screen Shot 2023-03-12 at 1 08 10 PM" src="https://user-images.githubusercontent.com/46941311/224544347-d72fb4ce-160b-43d2-b42b-9c7b1915b23d.png">

**Comment by stenya** [comment] 2023-04-05 11:08
@ajay-gh 

>  ... the settings window show no port numbers at all (as shown in the 2nd screenshot)

This is expected.
It is not possible to choose a port number for such configurations:
 - Multi-Hop connection
 - OpenVPN + obfsproxy

> ... either the main client window shows that the protocol/port selection has gone "back" to a combination I do never use (see first screen shot)   

Did you activate OpenVPN + obfsproxy?
Please note that obfsproxy requires a TCP connection. If you had selected a UDP port and then enabled obfsproxy, the port would be switched to TCP (without the possibility to choose a port number). After disabling obfsproxy, the selected port will remain TCP.

STR:
1. Select OpenVPN + any UDP port (e.g. UDP 2050)
2. Activate obfsproxy -> (the port will be switched to TCP; no port number selection allowed, as expected)
3. Deactivate obfsproxy -> (the port will stay selected as TCP + the first appropriate port number)

@gorkapernas FYI ^^^

**Comment by stenya** [comment] 2023-04-05 12:20
@ajay-gh 
In addition to the comment above:
Previously, we had an issue similar to what you reported in the first screenshot (https://github.com/ivpn/desktop-app/issues/250).
However, it has already been fixed in v3.10.14.

Please ensure you are using the latest IVPN version, or try reinstalling the application.
But if you continue to see the issue, I would ask you to provide us with more information: steps to reproduce would be really helpful.

**Comment by stenya** [comment] 2023-04-24 07:45
I am closing the ticket since there is nothing to change.

Please, feel free to reopen it if necessary.

**Closed by stenya** 2023-04-24 07:45 UTC
