### ISSUE TITLE
VPN Disconnects Frequently and Disables Apple Native Apps like iMessage and FaceTime

### ISSUE THREAD

**Issue by G0od102** [ivpn/desktop-app#394] opened 2024-09-18 11:36 UTC
Description:

I am experiencing frequent VPN disconnections using any available protocol. Additionally, once the VPN is connected, Apple native apps like iMessage and FaceTime become unusable. This issue is occurring on macOS Sequoia 15.0 (official release) with IVPN app version 3.14.14.

Steps to Reproduce:
Self-explanatory.

Expected Behavior:
The VPN should maintain a stable connection regardless of the protocol used.
iMessage and FaceTime should work as expected while the VPN is connected.

Actual Behavior:
The VPN disconnects every few minutes, regardless of the protocol used.
iMessage and FaceTime become unusable once the VPN is connected.

System Information:
macOS Version: Sequoia 15.0 (official release)
IVPN App Version: 3.14.14

Additional Information
Some other services seem to work like Apple Mail.
Restarting the VPN app and macOS does not resolve the issue.

**Comment by stenya** [comment] 2024-09-18 11:56
We are aware of the issue with iMessage and FaceTime on the latest macOS release (Sequoia 15.0) and are currently analyzing it.

**Comment by michaelharrigan** [comment] 2024-09-30 14:03
I have also been experiencing the same behavior, thank you for jumping on this! 

Are there any logs I can send, that could help further debug this?

**Comment by stenya** [comment] 2024-09-30 14:15
We are working on resolving the issues with Apple services (such as Messages and FaceTime) on macOS Sequoia. The solution will be available soon in the new IVPN Client for macOS.

The problem is more related to Apple (macOS). They have changed the way macOS communicates with Apple servers, and the OS does not respect the system's default routing configuration.

**Comment by michaelharrigan** [comment] 2024-09-30 14:20
> We are working on resolving the issues with Apple services (such as Messages and FaceTime) on macOS Sequoia. The solution will be available soon in the new IVPN Client for macOS.
> 
> 
> 
> The problem is more related to Apple (macOS). They have changed the way macOS communicates with Apple servers, and the OS does not respect the system's default routing configuration.

Ah, that makes sense as to why only their services were affected in this situation. Thanks again for the quick resolution! 🙏🏻

**Comment by stenya** [comment] 2024-10-03 07:26
@gorkapernas v3.14.20

**Comment by gorkapernas** [comment] 2024-10-10 12:55
Verified on version 3.14.23 (latest beta), the new Firewall option now allows iMessages and FaceTime to function as expected. Please note that you may need to reconnect the VPN for the firewall exceptions to take effect.

**Comment by stenya** [comment] 2024-10-15 08:13
Regarding the iMessage app issue on macOS Sequoia (v15.0):

While we have identified a potential solution, it is not yet stable. As a result, this fix will not be included in the official release until we find a reliable and robust solution. We are continuing to work towards a stable resolution.

However, Apple has addressed the issue in macOS Sequoia 15.1 Beta 6, so it should be resolved with the official release of macOS v15.1.

**Comment by G0od102** [comment] 2024-10-16 21:43
Would be really nice if we could have "local network sharing" option , right now obviously iPhone mirroring and some other services are unusable.

**Comment by stenya** [comment] 2024-11-05 15:57
Fix released in v3.14.29 (for WireGuard connections)

**Closed by stenya** 2024-11-05 15:57 UTC
