### ISSUE TITLE
Trusted Wifi but VPN stays connected

### ISSUE THREAD

**Issue by mucke5** [ivpn/desktop-app#11] opened 2021-04-24 19:17 UTC
# Bug report

## Describe your environment

* Device: Dell XPS 9380
* OS name and version: Ubuntu Budgie 20.04.2 LTS
* IVPN app version: 3.3.7

## Describe the problem
After the first boot and login, IVPN starts automatically at startup, but even if a known Wifi is set as trusted, the VPN connection remains active.

### Steps to reproduce:

0. set up IVPN to run automatically at startup.
1. connect to Wifi and set it up as trusted.
2. reboot
3. log in and see that VPN is connected and Wifi is marked as trusted.

### Expected Results:

* What did you expect to happen?
I expected the VPN connection to be disabled automatically.

**Comment by mucke5** [comment] 2021-05-20 11:35
@stenya 
![image](https://user-images.githubusercontent.com/13103826/118971631-f4881700-b96f-11eb-9b08-a55a41fa54a2.png)
![image](https://user-images.githubusercontent.com/13103826/118971742-11bce580-b970-11eb-90ca-2db22a664ffc.png)

**Comment by stenya** [comment] 2021-05-20 11:40
Thanks, @mucke5 for the report.
I will try to analyze your problem soon

**Comment by stenya** [comment] 2021-05-20 11:47
It will be also helpful for us to see the logs.
Can you, please, perform the next steps:
- enable `Allow logging` in application settings
- reproduce the problem (reboot and ensure that problem is reproduced)
- hare with us the log file: `/opt/ivpn/log/IVPN_Agent.log`

**Comment by mucke5** [comment] 2021-05-21 07:41
@stenya can you please confirm when you received the report?
![image](https://user-images.githubusercontent.com/13103826/119100781-99f6c580-ba18-11eb-8a10-488788c50184.png)

**Comment by stenya** [comment] 2021-05-21 08:03
@mucke5 Yes. We got the logs. Thank you.

**Comment by gorkapernas** [comment] 2021-05-26 09:47
Verified fixed on version 3.3.13, all platforms, the app remains disconnected after rebooting the machine if the network is set as "Trusted", regardless if the options "launch at login" + "autoconnect at launch" are enabled. 

The opposite happens, i.e. app connects to the VPN, if the network is set to "Untrusted". Please note that logging out from the app will reset to default certain app settings such as the network trust status.

@mucke5 please let us know if the issue is fixed on your side once we release the new version of the app. Thanks.

**Comment by mucke5** [comment] 2021-06-28 17:58
@gorkapernas & @stenya when will you release the new version of the app?

**Comment by stenya** [comment] 2021-06-28 18:02
I hope, we will do official release this week.

**Comment by stenya** [comment] 2021-06-29 11:01
v3.3.20 is released.
[Changelog](https://github.com/ivpn/desktop-app/blob/master/CHANGELOG.md)

**Closed by stenya** 2021-06-29 11:01 UTC
Labels: type: bug
