### ISSUE TITLE
(Windows) Old system tray icon not removed after application update

### ISSUE THREAD

**Issue by gorkapernas** [ivpn/desktop-app#34] opened 2021-05-18 08:38 UTC
### Description:
In the latest Windows version 3.3.10, when updating the app, the old system tray icon is not removed, so the user will end up with two ivpn system tray icons.

Please note that once moving the cursor over the icons, Windows removes the old system tray icon.

**Note:**
See attached screenshot for further details.

### Expected result:
Only one IVPN system tray icon should be shown after the update.

### Steps to reproduce:
1. Install on Windows version e.g. 3.2.69.
2. Launch the app.
3. Once the update notification pops-up, update the app.
4. When the update is complete, observe two system tray icons.

### Environment:
IVPN: 3.3.10
Platform: Windows 10

### Screenshot:
![image](https://user-images.githubusercontent.com/16647612/118619723-23ae5500-b7c5-11eb-97d5-3fb18c758b19.png)

**Comment by stenya** [comment] 2021-05-27 12:11
@gorkapernas beta version v3.3.14

The issue is fixed only for new upgrades.
It means it will work when upgrading FROM a fixed version (for example, it can be tested on downgrade  FIXED -> previous version )

**Comment by stenya** [comment] 2021-06-29 11:01
v3.3.20 is released.
[Changelog](https://github.com/ivpn/desktop-app/blob/master/CHANGELOG.md)

**Closed by stenya** 2021-06-29 11:01 UTC
Labels: platform: Windows, priority: low, type: bug
