### ISSUE TITLE
Better gaming experience using Split Tunneling [Linux]

### ISSUE THREAD

**Issue by candroid-man** [ivpn/desktop-app#147] opened 2022-04-23 03:58 UTC
# Feature request

Better compatibility with Steam and other popular game launchers and Split Tunneling.

## Description

Currently, when you try to utilize split tunneling, you have to launch the desired app through IVPN. Once that is done because it opens 2 apps, it doesn't actually affect the game, which can heavily impact gaming performance due to the nature of VPNs. If split tunneling worked like other VPNs, you would simply select which apps you do not want affected by the VPN and you can launch them as normal, but as of right now you are either forced to disable IVPN completely (which sometimes shuts off my internet for whatever reason until I restart without IVPN on startup), or get high ping and or network lag in high performance video games.

**Comment by stenya** [comment] 2022-04-25 14:33
@candroid-man  Please, clarify: 
Is the split-tunneling not working at all for you when you start Steam out from the IVPN application?

Or you just do not like the fact that applications have to be started out from the IVPN app?
This is the nature of how split-tunneling works on Linux.
In order to guarantee that the application/command (and its all child processes) are split out from a VPN connection - the application must be started in a specific way.

You wrote `If split tunneling worked like other VPNs, you would simply select which apps you do not want affected by the VPN and you can launch them as normal`.
Can you, please, give us an example of VPN applications you know that allow doing that (on Linux)?

**Comment by stenya** [comment] 2022-05-04 14:48
@candroid-man Hi!
I suppose the problem is solved. I am closing the ticket.
Please, feel free to reopen it if required.

**Closed by stenya** 2022-05-04 14:48 UTC
