### ISSUE TITLE
(Windows) Unable to logout.

### ISSUE THREAD

**Issue by ssstroke** [ivpn/desktop-app#343] opened 2023-12-18 09:41 UTC
# Bug report

## Describe your environment

* Device: HP Laptop 
* OS name and version: Windows 11 22H2
* IVPN app version: 3.13.4

## Describe the problem

I used to be always logged in on 2 devices. Some day I had to log in on another computer, so when I logged in the app suggested me if I want to log out from all other devices, to which I agreed. Now I switched back to my main PC, started the app, expecting it to suggest me log out from all other devices, but it did not. It does not connect to any servers (as I exceeded the limit, I suppose), but it it also stuck when trying to log out. The animation just stuck forever. I tried uninstalling the app, but the process is also stuck at `Logout` phase. I tried manually deleting the app folder, but the Windows said that this folder is in use currently thus can not be deleted. I tried launching installer, and in the beginning it seemed to work fine, but then it gave an `"Error opening file for writing: C:\Program Files\IVPN Client\v2ray\v2ray.exe"`.

**FIX**: As I am writing this, I decided to kill "v2ray" process and it worked! Installer did success and I have been logged out. Now I am able to log back in and connect.
Though I still think this problem should be fixed.

### Steps to reproduce:

1. Be logged in on 2 devices (I suppose 7, if you are using PRO, will work) . Let's call them A (PC) and B (Android).
2. Try logging in on the third device (let's call it X) and accept logging out from all of the other devices (A and B).
3. Log in on B device (now you are logged on B and X).
4. Try opening app on A device.

### Observed Results:

* Unable to connect to any server and logout.

### Expected Results:

* Message suggesting me to log out from other devices.

**Comment by stenya** [comment] 2024-02-01 13:57
Corrected STR:
1) Login
2) Force logout on another device (or use device management to logout device)
3) Regenerate WG keys (Note! WG keys regeneration might also start automatically in the background)

**Comment by stenya** [comment] 2024-02-01 18:27
v3.14.0

**Comment by gorkapernas** [comment] 2024-02-08 11:05
Verified fixed on the the latest beta v3.14.2, there was an issue when the client attempted to rotate the WireGuard key (either manually or automatically in the background) without an active session (e.g. the device has been forced logout). In this case, the app hung on logging out permanently. 
The issue is currently solved, if the app attempts to rotate a WireGuard key without an active session, an error is presented and the user is logged out.

**Comment by stenya** [comment] 2024-02-08 12:44
v3.14.2 released

**Closed by stenya** 2024-02-08 12:44 UTC
Labels: type: bug
